label plugin removal restricts authors from adding some tags
opensourceways/test-infra pull request #52
Opened 2021-04-14 02:10 UTC by xwz123

Due to the issue of the gitee API, first remove the restriction on the PR author to add some designated labels

2021-04-14 02:37 UTC, zengchen1024 commented on prow/gitee-plugins/label/action.go
> +	return ia.client.CreateGiteeIssueComment(org, repo, ia.issueNumber(), comment)
Could you change the function's name to `CreateIssueComment`

2021-04-14 02:39 UTC, zengchen1024 commented on prow/gitee/client.go
> +func (c *client) GetPullRequestOperateLogs(org, repo string, number int32) ([]sdk.OperateLog, error) {
this function is not used

2021-04-14 03:55 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +	repoLabels, err := l.ghc.GetRepoLabels(e.Repository.Namespace, e.Repository.Path)
use GetOwnerAndRepoByEvent to fetch org and repo

2021-04-14 03:55 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		RepoLabelsExisting.Insert(strings.ToLower(l.Name))
why do you change it to lowercase.

2021-04-14 03:55 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		additionalLabels = append(additionalLabels, cfg.AdditionalLabels...)
no need to generate a new slice

2021-04-14 03:55 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		if plugins.HasLabel(labelToAdd, labels) {
change labels to a map to increase efficiency

2021-04-14 03:55 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		canAddLabel = append(canAddLabel, labelToAdd)
it will add another label, such as abc, but the ABC is allowed.

2021-04-14 03:55 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		if !plugins.HasLabel(labelToRemove, labels) {
change labels to a map to increase efficiency

2021-04-14 06:15 UTC, xwz123 commented on prow/gitee-plugins/label/action.go
> +	return ia.client.CreateGiteeIssueComment(org, repo, ia.issueNumber(), comment)
I will submit a PR specifically to solve.

2021-04-14 08:24 UTC, zengchen1024 commented on prow/gitee-plugins/util.go
> +	return owner, repo, nil
var repository *gitee.ProjectHook
	switch t := e.(type) {
	case *gitee.PullRequestEvent:
		repository = t.Repository
	case *gitee.NoteEvent:
		repository = t.Repository
	case *gitee.PushEvent:
		repository = t.Repository
	case *gitee.IssueEvent:
		repository = t.Repository
	default:
		return "", "", fmt.Errorf("not support event type")
	}
	
	if repository == nil {
		return "", "", fmt.Errorf("no repository")
	}

	org := repository.Namespace
	repo := repository.Path

	if org == "" || repo == "" {
		return "", "", fmt.Errorf("owner or repo is empty")
	}
	return org, repo, nil

2021-04-14 08:27 UTC, zengchen1024 commented on prow/gitee-plugins/label/check.go
> +package label
remove this file to clear-label.go

2021-04-14 08:30 UTC, zengchen1024 commented on prow/gitee-plugins/label/check.go
> +	number := e.PullRequest.Number
move `number := e.PullRequest.Number` to line 32. The variable should be close to the position where it is be used.

2021-04-14 08:31 UTC, zengchen1024 commented on prow/gitee-plugins/label/check.go
> +	return l.ghc.CreatePRComment(org, repo, int(number), comment)
comment := fmt.Sprintf(
"This pull request source branch has changed,label(s): **%s** has been removed.",strings.Join(needClear, ",")
)

2021-04-14 08:34 UTC, zengchen1024 reviewed
need change

2021-04-14 08:52 UTC, zengchen1024 requested changes

2021-04-14 08:52 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +			noSuchLabelsOnIssue = append(noSuchLabelsOnIssue, labelToRemove)
continue directly

2021-04-15 01:54 UTC, zengchen1024 commented on prow/gitee-plugins/label/clear_label.go
> +	number := e.PullRequest.Number
number := (int)e.PullRequest.Number

2021-04-15 02:02 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +func addMatchLabels(matches [][]string, labels, repoLabels map[string]string, action noteEventAction, log *logrus.Entry) []string {
s/labels/currentLabels/

2021-04-15 02:05 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +	return noSuchLabelsInRepo
if len(canAddLabel) == 0 {
		if err := action.addLabel(canAddLabel); err != nil {
			log.WithError(err).Errorf("Gitee failed to add the following label: %s", strings.Join(canAddLabel, ","))
		}
	}
	return noSuchLabelsInRepo

2021-04-15 02:07 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +	}
if label, ok := repoLabels[labelToAdd]; !ok {
			noSuchLabelsInRepo = append(noSuchLabelsInRepo, labelToAdd)
		} else {
			canAddLabel = append(canAddLabel, label)
		}

2021-04-15 02:08 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		}
if label, ok := labels[labelToRemove]; ok {
			if err := action.removeLabel(label); err != nil {
				log.WithError(err).Errorf("Gitee failed to add the following label: %s", label)
			}
		}

2021-04-15 02:10 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +	removeMatchLabels(removeLabelMatches, issueLabels, action, log)
exchange the position between `addMatchLabels` and `removeMatchLabels` to make `noSuchLabelsInRepo` to be close to line 165

2021-04-15 02:10 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +		log.Infof("Labels missing in repo: %v", noSuchLabelsInRepo)
it is better not to add log here

2021-04-15 02:11 UTC, zengchen1024 commented on prow/gitee-plugins/label/label.go
> +			strings.Join(noSuchLabelsInRepo, ", "))
format

2021-04-15 02:11 UTC, zengchen1024 commented on prow/gitee-plugins/util.go
> +
remove blank line

2021-04-15 02:17 UTC, zengchen1024 requested changes
need change

2021-04-15 08:27 UTC, xwz123 commented on prow/gitee-plugins/label/clear_label.go
> +		log.Debug("No labels to be cleared are configured when PR source branch has changed")
rm log

2021-04-15 08:29 UTC, xwz123 commented on prow/gitee-plugins/label/clear_label.go
> +		"This pull request source branch has changed,label(s): **%s** has been removed.", strings.Join(needClear, ","))
s/**%s**/%s

2021-04-19 07:52 UTC, closed without merging