gitee lifecycle plugin
opensourceways/test-infra pull request #53
Opened 2021-04-14 11:50 UTC by xwz123

1. support close pr and issue command.
2. support reopen issue command.

2021-04-15 02:27 UTC, zengchen1024 commented on prow/gitee/client.go
> +		State: "open",
Is there any variable from gitee library to be on behalf of `open`

2021-04-15 02:27 UTC, zengchen1024 commented on prow/gitee/client.go
> +		State: "closed",
Is there any variable from gitee library to be on behalf of `close`

2021-04-15 02:28 UTC, zengchen1024 commented on prow/gitee/client.go
> +		State:"closed",
Is there any variable from gitee library to be on behalf of `closed`

2021-04-15 02:30 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +	if err != nil {
ignore error

2021-04-15 02:32 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +		response := "You can't reopen an issue/PR unless you authored it or you are a collaborator."
You can't reopen an issue or a PR unless you are the author of it or a collaborator

2021-04-15 02:33 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +		log.Infof("Commenting \"%s\".", response)
don't write log

2021-04-15 02:34 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +		response := "You can't reopen an issue/PR unless you authored it or you are a collaborator."
s/!isAuthor/e.Issue.User.Login != commentAuthor

2021-04-15 02:35 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +	if isPr(*e.NoteableType) || e.Issue.State != "closed" {
isPr doesn't mean the event is for issue.

2021-04-15 02:37 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +		return err
if err = gc.ReopenIssue(org, repo, number); err != nil {

2021-04-15 02:38 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +		response := "You can't reopen an issue/PR unless you authored it or you are a collaborator."
if !isAuthor {
	isCollaborator, err := gc.IsCollaborator(org, repo, commentAuthor)
	if err != nil {
		log.WithError(err).Errorf("Failed IsCollaborator(%s, %s, %s)", org, repo, commentAuthor)
	}
        if !isCollaborator{
}
}

2021-04-15 02:40 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/lifecycle.go
> +		WhoCanUse:   "Authors and collaborators on the repository can trigger this command.",
collaborators of the repository

2021-04-15 02:41 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/lifecycle.go
> +	if *(e.Action) != "comment" || (!isPr(eType) && eType != "Issue") {
!isPr(eType) && eType != "Issue"
can new a function of isIssue

2021-04-15 02:46 UTC, zengchen1024 requested changes
need change

2021-04-15 02:46 UTC, xwz123 commented on prow/gitee-plugins/lifecycle/reopen.go
> +	if isPr(*e.NoteableType) || e.Issue.State != "closed" {
Already judged at the event entrance

2021-04-15 06:58 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/close.go
> +		response := "You can't close an  issue unless you authored it or you are a collaborator."
You can't close an issue unless you are the author of it or a collaborator

2021-04-15 06:59 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/close.go
> +		response := "You can't reopen an issue unless you are the author of it or a collaborator"
ditto

2021-04-15 07:01 UTC, zengchen1024 commented on prow/gitee/type.go
> +	return noteType == "issue"
Issue

2021-04-15 07:03 UTC, zengchen1024 reviewed
need change

2021-04-15 11:12 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/lifecycle.go
> +		if err := closePullRequest(l.gec, log, e); err != nil {
return closePullRequest(l.gec, log, e)

2021-04-16 09:14 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) IsCreateCommentEvent() bool {
s/IsCreateCommentEvent/IsCreatingComment

2021-04-16 09:15 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) IssueIsClosed() bool {
s/IssueIsClosed/IsIssueClosed/

2021-04-16 09:15 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) IssueIsOpen() bool {
s/IssueIsOpen/IsIssueOpened

2021-04-16 09:16 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) PRIsOpen() bool {
s/PRIsOpen/IsPROpened

2021-04-16 09:17 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) CommenterIsIssueAuthor() bool {
s/CommenterIsIssueAuthor/IsCommenterSameAsIssueAuthor

2021-04-16 09:17 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) CommenterIsPRAuthor() bool {
s/CommenterIsPRAuthor/IsCommenterSameAsPRAuthor/

2021-04-16 09:18 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) CommenterIsAuthor() bool {
delete

2021-04-16 09:18 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) GetCommenter() string {
s/GetCommenter/Commenter

2021-04-16 09:18 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) GetPRNumber() int {
s/GetPRNumber/PRNumber

2021-04-16 09:19 UTC, zengchen1024 commented on prow/gitee/noteevent.go
> +func (ne *NoteEvent) GetIssueNumber() string {
s/GetIssueNumber/IssueNumber/

2021-04-16 09:23 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/reopen.go
> +		org, repo, number, plugins.FormatResponseRaw(e.Comment.Body, e.Comment.HtmlUrl, commentAuthor, "Reopened this issue."))
response := plugins.FormatResponseRaw(e.Comment.Body, e.Comment.HtmlUrl, commentAuthor, "Closed this PR.")
	return gc.CreatePRComment(org, repo, number, response)

2021-04-16 09:29 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/close.go
> +}
func isAuthorOrCollaborator(org, repo, author string, ne *gitee.NoteEvent, gh giteeClient, log *logrus.Entry) bool {
	if author == ne.Commenter() {
		return true
	}
	isCollaborator, err := gh.IsCollaborator(org, repo, ne.Commenter())
	if err != nil {
		log.WithError(err).Errorf("Failed IsCollaborator(%s, %s, %s)", org, repo,  ne.Commenter())
	}
	return isCollaborator
}

2021-04-16 09:30 UTC, zengchen1024 commented on prow/gitee/BUILD.bazel
> +        "noteevent.go",
can change another name

2021-04-16 09:30 UTC, zengchen1024 commented on prow/gitee-plugins/lifecycle/lifecycle.go
> +func (l *lifecycle) handleIssue(e *sdk.NoteEvent, log *logrus.Entry) error {
s/e/ne

2021-04-16 09:36 UTC, merged